openapi: 3.0.0
info:
  description: |
    Product service API
  version: "1.0.0"
  title: Product service
  contact:
    email: daniiil.ponomarev@gmail.com
  license:
    name: Apache 2.0
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
servers:
  - description: AWS server
    url: "https://52m4snbje6.execute-api.eu-west-1.amazonaws.com"
tags:
  - name: product-service
    description: Get products from API for the home-office-store application
paths:
  "/products":
    get:
      tags:
        - product-service
      summary: Get all products
      operationId: getProductsList
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductsApiResponse"
  "/products/{productId}":
    get:
      tags:
        - product-service
      summary: Find product by ID
      description: Returns a single product
      operationId: getProductsById
      parameters:
        - name: productId
          in: path
          description: ID of product to return
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductApiResponse"
        "400":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductApiBadResponse"
        "404":
          description: Product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductApiBadResponse"
externalDocs:
  description: Find out more about Product service API
  url: "https://github.com/daniiilponomarev/be-your-home-office"
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - description
        - title
        - price
        - imageUrl
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        price:
          type: integer
          format: int64
    ProductsApiResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: true
          description: Response status
        products:
          type: array
          items:
            $ref: "#/components/schemas/Product"
        timestamp:
          type: string
    ProductApiResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: true
        product:
          $ref: "#/components/schemas/Product"
        timestamp:
          type: string
    ProductApiBadResponse:
      type: object
      properties:
        ok:
          type: boolean
          default: false
        message:
          type: string
        timestamp:
          type: string
