service: import-service

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  environment:
    SQS_QUEUE_URL:
      Fn::ImportValue: ProductService-QueueUrl

iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - 's3:ListBucket'
    Resource: 'arn:aws:s3:::your-home-office-files1'
  - Effect: 'Allow'
    Action:
      - 's3:ListBucket'
      - 's3:GetObject'
      - 's3:PutObject'
    Resource: 'arn:aws:s3:::your-home-office-files1/*'
  - Effect: Allow
    Action:
      - "sqs:*"
    Resource:
      'Fn::ImportValue': ProductService-QueueUrl

custom:
  bundle:
    sourcemaps: false

functions:
  importProductsFile:
    handler: importProductsFile/index.handler
    events:
      - httpApi:
          path: /import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
    environment:
      S3_BUCKET: 'your-home-office-files1'

  importFileParser:
    handler: importFileParser/index.handler
    events:
      - s3:
          bucket: 'your-home-office-files1'
          event: s3:ObjectCreated:*
          cors: true
          rules:
            - prefix: uploaded/
    environment:
      S3_BUCKET: 'your-home-office-files1'
      BUCKET_SOURCE: 'uploaded'
      BUCKET_DIST: 'parsed'
